name: Android Build

on:
  pull_request:
    branches:
      - master
  push:

env:
  CI: true
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dkotlin.incremental=false
  TERM: dumb

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Spotless Apply
        run: ./gradlew spotlessApply

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assembleDebug
